//
//  MapInteractor.swift
//  CurrentAddress
//
//  Created by vitor.ferrazvarela on 02/05/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import MapKit

protocol MapBusinessLogic
{
    func doSomething(request: Map.Something.Request)
    func requestForCurrentLocation(request: Map.RequestForCurrentLocation.Request)
}

protocol MapDataStore
{
    //var name: String { get set }
}

class MapInteractor: NSObject, MapBusinessLogic, MapDataStore, CLLocationManagerDelegate
{
    
    var presenter: MapPresentationLogic?
    var worker: MapWorker?
    //var name: String = ""
    let locationManager = CLLocationManager()
    // MARK: Do something
    
    func doSomething(request: Map.Something.Request)
    {
        worker = MapWorker()
        worker?.doSomeWork()
        
        let response = Map.Something.Response()
        presenter?.presentSomething(response: response)
    }
    
    // MARK: Request for current location
    func requestForCurrentLocation(request: Map.RequestForCurrentLocation.Request) {
        locationManager.delegate = self
        locationManager.requestAlwaysAuthorization()
    }
    func locationManager(_ manager: CLLocationManager, didChangeAuthorization status: CLAuthorizationStatus) {
        var response: Map.RequestForCurrentLocation.Response

        switch status {
        case .authorizedWhenInUse:
            response = Map.RequestForCurrentLocation.Response(success: true)
        case .denied, .restricted:
            response = Map.RequestForCurrentLocation.Response(success: false)
        default:
            return
        }
        presenter?.requestForCurrentLocation(response: response)
        
    }
}
