//
//  MapWorker.swift
//  CurrentAddress
//
//  Created by vitor.ferrazvarela on 02/05/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class MapWorker
{
  func doSomeWork()
  {
  }
}
