//
//  PlacemarkViewControllerTests.swift
//  CurrentAddress
//
//  Created by vitor.ferrazvarela on 07/05/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import CurAddress
import XCTest

class PlacemarkViewControllerTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: PlacemarkViewController!
  var window: UIWindow!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    window = UIWindow()
    setupPlacemarkViewController()
  }
  
  override func tearDown()
  {
    window = nil
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupPlacemarkViewController()
  {
    let bundle = Bundle.main
    let storyboard = UIStoryboard(name: "MainStoryboard", bundle: bundle)
    sut = storyboard.instantiateViewController(withIdentifier: "PlacemarkViewController") as! PlacemarkViewController
  }
  
  func loadView()
  {
    window.addSubview(sut.view)
    RunLoop.current.run(until: Date())
  }
  
  // MARK: Test doubles
  
  
  // MARK: Tests

}
