//
//  PlacemarkPresenter.swift
//  CurrentAddress
//
//  Created by vitor.ferrazvarela on 05/05/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PlacemarkPresentationLogic
{
    func presentSomething(response: Placemark.Something.Response)
    func presentPhysicalAddress(response: Placemark.ShowPhysicalAddress.Response)
}

class PlacemarkPresenter: PlacemarkPresentationLogic
{
    weak var viewController: PlacemarkDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: Placemark.Something.Response)
    {
        let viewModel = Placemark.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
    
    // MARK: Present Physical Address
    func presentPhysicalAddress(response: Placemark.ShowPhysicalAddress.Response) {
        let viewModel = Placemark.ShowPhysicalAddress.ViewModel(placemark: response.placemark)
        viewController?.displayPhysicalAddress(viewModel: viewModel)
        
    }
}
